name: AutoQNDXX

on:
  schedule:
    # Run at 8:00 on every Tuesday.
    - cron: '25 15  * * 1'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.8
           
      - name: 'Install requirements'
        run: pip install -r requirements.txt
        
      - name: 'Working'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ORG_ID: ${{secrets.ORG_ID}}
          REMOTE_CONFIG: ${{secrets.REMOTE_CONFIG}}
        run: |
          python main.py
        
